name: Android Security Scan (Build + Audit)

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  security-audit:
    name: Build & Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Clone the Source Code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Setup Java Environment (Required for Android Build)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # [Debug] Check file structure (Helps to find where gradlew is)
      - name: List files (Debug)
        run: ls -R

      # 3. Grant Permissions to Gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build the APK (Debug Variant)
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. Run Droid-LLM-Hunter Scanner
      - name: Droid LLM Hunter Scan
        uses: mubtakir-lazuardi/droid-llm-hunter@main
        with:
          # Point to the APK generated in Step 4
          apk-path: app/build/outputs/apk/debug/app-debug.apk
          provider: "gemini"
          # Ensure GEMINI_KEY is set in Repo Settings > Secrets
          api-key: ${{ secrets.GEMINI_KEY }}

      # 6. Upload the Security Report
      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always() # Upload even if vulnerabilities are found
        with:
          name: security-report
          path: droid-llm-report.json
